*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 06.11.2020 at 12:51:54
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZSWL_V_PARC.....................................*
FORM GET_DATA_ZSWL_V_PARC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSWL_T_PARC WHERE
(VIM_WHERETAB) .
    CLEAR ZSWL_V_PARC .
ZSWL_V_PARC-MANDT =
ZSWL_T_PARC-MANDT .
ZSWL_V_PARC-LGNUM =
ZSWL_T_PARC-LGNUM .
ZSWL_V_PARC-ID1 =
ZSWL_T_PARC-ID1 .
ZSWL_V_PARC-ID2 =
ZSWL_T_PARC-ID2 .
ZSWL_V_PARC-SEQNO =
ZSWL_T_PARC-SEQNO .
ZSWL_V_PARC-TYPE =
ZSWL_T_PARC-TYPE .
ZSWL_V_PARC-SIGN =
ZSWL_T_PARC-SIGN .
ZSWL_V_PARC-OPT =
ZSWL_T_PARC-OPT .
ZSWL_V_PARC-LOW =
ZSWL_T_PARC-LOW .
ZSWL_V_PARC-HIGH =
ZSWL_T_PARC-HIGH .
ZSWL_V_PARC-VALIDFROM =
ZSWL_T_PARC-VALIDFROM .
ZSWL_V_PARC-VALIDUNTIL =
ZSWL_T_PARC-VALIDUNTIL .
ZSWL_V_PARC-REMARK =
ZSWL_T_PARC-REMARK .
<VIM_TOTAL_STRUC> = ZSWL_V_PARC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSWL_V_PARC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSWL_V_PARC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSWL_V_PARC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSWL_T_PARC WHERE
  LGNUM = ZSWL_V_PARC-LGNUM AND
  ID1 = ZSWL_V_PARC-ID1 AND
  ID2 = ZSWL_V_PARC-ID2 AND
  TYPE = ZSWL_V_PARC-TYPE AND
  SEQNO = ZSWL_V_PARC-SEQNO .
    IF SY-SUBRC = 0.
    DELETE ZSWL_T_PARC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSWL_T_PARC WHERE
  LGNUM = ZSWL_V_PARC-LGNUM AND
  ID1 = ZSWL_V_PARC-ID1 AND
  ID2 = ZSWL_V_PARC-ID2 AND
  TYPE = ZSWL_V_PARC-TYPE AND
  SEQNO = ZSWL_V_PARC-SEQNO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSWL_T_PARC.
    ENDIF.
ZSWL_T_PARC-MANDT =
ZSWL_V_PARC-MANDT .
ZSWL_T_PARC-LGNUM =
ZSWL_V_PARC-LGNUM .
ZSWL_T_PARC-ID1 =
ZSWL_V_PARC-ID1 .
ZSWL_T_PARC-ID2 =
ZSWL_V_PARC-ID2 .
ZSWL_T_PARC-SEQNO =
ZSWL_V_PARC-SEQNO .
ZSWL_T_PARC-TYPE =
ZSWL_V_PARC-TYPE .
ZSWL_T_PARC-SIGN =
ZSWL_V_PARC-SIGN .
ZSWL_T_PARC-OPT =
ZSWL_V_PARC-OPT .
ZSWL_T_PARC-LOW =
ZSWL_V_PARC-LOW .
ZSWL_T_PARC-HIGH =
ZSWL_V_PARC-HIGH .
ZSWL_T_PARC-VALIDFROM =
ZSWL_V_PARC-VALIDFROM .
ZSWL_T_PARC-VALIDUNTIL =
ZSWL_V_PARC-VALIDUNTIL .
ZSWL_T_PARC-REMARK =
ZSWL_V_PARC-REMARK .
    IF SY-SUBRC = 0.
    UPDATE ZSWL_T_PARC ##WARN_OK.
    ELSE.
    INSERT ZSWL_T_PARC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSWL_V_PARC-UPD_FLAG,
STATUS_ZSWL_V_PARC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSWL_V_PARC.
  SELECT SINGLE * FROM ZSWL_T_PARC WHERE
LGNUM = ZSWL_V_PARC-LGNUM AND
ID1 = ZSWL_V_PARC-ID1 AND
ID2 = ZSWL_V_PARC-ID2 AND
TYPE = ZSWL_V_PARC-TYPE AND
SEQNO = ZSWL_V_PARC-SEQNO .
ZSWL_V_PARC-MANDT =
ZSWL_T_PARC-MANDT .
ZSWL_V_PARC-LGNUM =
ZSWL_T_PARC-LGNUM .
ZSWL_V_PARC-ID1 =
ZSWL_T_PARC-ID1 .
ZSWL_V_PARC-ID2 =
ZSWL_T_PARC-ID2 .
ZSWL_V_PARC-SEQNO =
ZSWL_T_PARC-SEQNO .
ZSWL_V_PARC-TYPE =
ZSWL_T_PARC-TYPE .
ZSWL_V_PARC-SIGN =
ZSWL_T_PARC-SIGN .
ZSWL_V_PARC-OPT =
ZSWL_T_PARC-OPT .
ZSWL_V_PARC-LOW =
ZSWL_T_PARC-LOW .
ZSWL_V_PARC-HIGH =
ZSWL_T_PARC-HIGH .
ZSWL_V_PARC-VALIDFROM =
ZSWL_T_PARC-VALIDFROM .
ZSWL_V_PARC-VALIDUNTIL =
ZSWL_T_PARC-VALIDUNTIL .
ZSWL_V_PARC-REMARK =
ZSWL_T_PARC-REMARK .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSWL_V_PARC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSWL_V_PARC-LGNUM TO
ZSWL_T_PARC-LGNUM .
MOVE ZSWL_V_PARC-ID1 TO
ZSWL_T_PARC-ID1 .
MOVE ZSWL_V_PARC-ID2 TO
ZSWL_T_PARC-ID2 .
MOVE ZSWL_V_PARC-TYPE TO
ZSWL_T_PARC-TYPE .
MOVE ZSWL_V_PARC-SEQNO TO
ZSWL_T_PARC-SEQNO .
MOVE ZSWL_V_PARC-MANDT TO
ZSWL_T_PARC-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSWL_T_PARC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSWL_T_PARC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSWL_T_PARC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZSWL_V_PARDF....................................*
FORM GET_DATA_ZSWL_V_PARDF.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSWL_T_PARDF WHERE
(VIM_WHERETAB) .
    CLEAR ZSWL_V_PARDF .
ZSWL_V_PARDF-MANDT =
ZSWL_T_PARDF-MANDT .
ZSWL_V_PARDF-ID1 =
ZSWL_T_PARDF-ID1 .
ZSWL_V_PARDF-ID2 =
ZSWL_T_PARDF-ID2 .
ZSWL_V_PARDF-USAGE_TYPE =
ZSWL_T_PARDF-USAGE_TYPE .
ZSWL_V_PARDF-CLASS =
ZSWL_T_PARDF-CLASS .
ZSWL_V_PARDF-REMARK =
ZSWL_T_PARDF-REMARK .
<VIM_TOTAL_STRUC> = ZSWL_V_PARDF.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSWL_V_PARDF .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSWL_V_PARDF.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSWL_V_PARDF-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSWL_T_PARDF WHERE
  ID1 = ZSWL_V_PARDF-ID1 AND
  ID2 = ZSWL_V_PARDF-ID2 AND
  USAGE_TYPE = ZSWL_V_PARDF-USAGE_TYPE .
    IF SY-SUBRC = 0.
    DELETE ZSWL_T_PARDF .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSWL_T_PARDF WHERE
  ID1 = ZSWL_V_PARDF-ID1 AND
  ID2 = ZSWL_V_PARDF-ID2 AND
  USAGE_TYPE = ZSWL_V_PARDF-USAGE_TYPE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSWL_T_PARDF.
    ENDIF.
ZSWL_T_PARDF-MANDT =
ZSWL_V_PARDF-MANDT .
ZSWL_T_PARDF-ID1 =
ZSWL_V_PARDF-ID1 .
ZSWL_T_PARDF-ID2 =
ZSWL_V_PARDF-ID2 .
ZSWL_T_PARDF-USAGE_TYPE =
ZSWL_V_PARDF-USAGE_TYPE .
ZSWL_T_PARDF-CLASS =
ZSWL_V_PARDF-CLASS .
ZSWL_T_PARDF-REMARK =
ZSWL_V_PARDF-REMARK .
    IF SY-SUBRC = 0.
    UPDATE ZSWL_T_PARDF ##WARN_OK.
    ELSE.
    INSERT ZSWL_T_PARDF .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSWL_V_PARDF-UPD_FLAG,
STATUS_ZSWL_V_PARDF-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSWL_V_PARDF.
  SELECT SINGLE * FROM ZSWL_T_PARDF WHERE
ID1 = ZSWL_V_PARDF-ID1 AND
ID2 = ZSWL_V_PARDF-ID2 AND
USAGE_TYPE = ZSWL_V_PARDF-USAGE_TYPE .
ZSWL_V_PARDF-MANDT =
ZSWL_T_PARDF-MANDT .
ZSWL_V_PARDF-ID1 =
ZSWL_T_PARDF-ID1 .
ZSWL_V_PARDF-ID2 =
ZSWL_T_PARDF-ID2 .
ZSWL_V_PARDF-USAGE_TYPE =
ZSWL_T_PARDF-USAGE_TYPE .
ZSWL_V_PARDF-CLASS =
ZSWL_T_PARDF-CLASS .
ZSWL_V_PARDF-REMARK =
ZSWL_T_PARDF-REMARK .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSWL_V_PARDF USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSWL_V_PARDF-ID1 TO
ZSWL_T_PARDF-ID1 .
MOVE ZSWL_V_PARDF-ID2 TO
ZSWL_T_PARDF-ID2 .
MOVE ZSWL_V_PARDF-USAGE_TYPE TO
ZSWL_T_PARDF-USAGE_TYPE .
MOVE ZSWL_V_PARDF-MANDT TO
ZSWL_T_PARDF-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSWL_T_PARDF'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSWL_T_PARDF TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSWL_T_PARDF'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZSWL_V_PARMD....................................*
FORM GET_DATA_ZSWL_V_PARMD.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSWL_T_PARMD WHERE
(VIM_WHERETAB) .
    CLEAR ZSWL_V_PARMD .
ZSWL_V_PARMD-MANDT =
ZSWL_T_PARMD-MANDT .
ZSWL_V_PARMD-LGNUM =
ZSWL_T_PARMD-LGNUM .
ZSWL_V_PARMD-ID1 =
ZSWL_T_PARMD-ID1 .
ZSWL_V_PARMD-ID2 =
ZSWL_T_PARMD-ID2 .
ZSWL_V_PARMD-SEQNO =
ZSWL_T_PARMD-SEQNO .
ZSWL_V_PARMD-TYPE =
ZSWL_T_PARMD-TYPE .
ZSWL_V_PARMD-SIGN =
ZSWL_T_PARMD-SIGN .
ZSWL_V_PARMD-OPT =
ZSWL_T_PARMD-OPT .
ZSWL_V_PARMD-LOW =
ZSWL_T_PARMD-LOW .
ZSWL_V_PARMD-HIGH =
ZSWL_T_PARMD-HIGH .
ZSWL_V_PARMD-VALIDFROM =
ZSWL_T_PARMD-VALIDFROM .
ZSWL_V_PARMD-VALIDUNTIL =
ZSWL_T_PARMD-VALIDUNTIL .
ZSWL_V_PARMD-REMARK =
ZSWL_T_PARMD-REMARK .
<VIM_TOTAL_STRUC> = ZSWL_V_PARMD.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSWL_V_PARMD .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSWL_V_PARMD.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSWL_V_PARMD-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSWL_T_PARMD WHERE
  LGNUM = ZSWL_V_PARMD-LGNUM AND
  ID1 = ZSWL_V_PARMD-ID1 AND
  ID2 = ZSWL_V_PARMD-ID2 AND
  TYPE = ZSWL_V_PARMD-TYPE AND
  SEQNO = ZSWL_V_PARMD-SEQNO .
    IF SY-SUBRC = 0.
    DELETE ZSWL_T_PARMD .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSWL_T_PARMD WHERE
  LGNUM = ZSWL_V_PARMD-LGNUM AND
  ID1 = ZSWL_V_PARMD-ID1 AND
  ID2 = ZSWL_V_PARMD-ID2 AND
  TYPE = ZSWL_V_PARMD-TYPE AND
  SEQNO = ZSWL_V_PARMD-SEQNO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSWL_T_PARMD.
    ENDIF.
ZSWL_T_PARMD-MANDT =
ZSWL_V_PARMD-MANDT .
ZSWL_T_PARMD-LGNUM =
ZSWL_V_PARMD-LGNUM .
ZSWL_T_PARMD-ID1 =
ZSWL_V_PARMD-ID1 .
ZSWL_T_PARMD-ID2 =
ZSWL_V_PARMD-ID2 .
ZSWL_T_PARMD-SEQNO =
ZSWL_V_PARMD-SEQNO .
ZSWL_T_PARMD-TYPE =
ZSWL_V_PARMD-TYPE .
ZSWL_T_PARMD-SIGN =
ZSWL_V_PARMD-SIGN .
ZSWL_T_PARMD-OPT =
ZSWL_V_PARMD-OPT .
ZSWL_T_PARMD-LOW =
ZSWL_V_PARMD-LOW .
ZSWL_T_PARMD-HIGH =
ZSWL_V_PARMD-HIGH .
ZSWL_T_PARMD-VALIDFROM =
ZSWL_V_PARMD-VALIDFROM .
ZSWL_T_PARMD-VALIDUNTIL =
ZSWL_V_PARMD-VALIDUNTIL .
ZSWL_T_PARMD-REMARK =
ZSWL_V_PARMD-REMARK .
    IF SY-SUBRC = 0.
    UPDATE ZSWL_T_PARMD ##WARN_OK.
    ELSE.
    INSERT ZSWL_T_PARMD .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSWL_V_PARMD-UPD_FLAG,
STATUS_ZSWL_V_PARMD-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSWL_V_PARMD.
  SELECT SINGLE * FROM ZSWL_T_PARMD WHERE
LGNUM = ZSWL_V_PARMD-LGNUM AND
ID1 = ZSWL_V_PARMD-ID1 AND
ID2 = ZSWL_V_PARMD-ID2 AND
TYPE = ZSWL_V_PARMD-TYPE AND
SEQNO = ZSWL_V_PARMD-SEQNO .
ZSWL_V_PARMD-MANDT =
ZSWL_T_PARMD-MANDT .
ZSWL_V_PARMD-LGNUM =
ZSWL_T_PARMD-LGNUM .
ZSWL_V_PARMD-ID1 =
ZSWL_T_PARMD-ID1 .
ZSWL_V_PARMD-ID2 =
ZSWL_T_PARMD-ID2 .
ZSWL_V_PARMD-SEQNO =
ZSWL_T_PARMD-SEQNO .
ZSWL_V_PARMD-TYPE =
ZSWL_T_PARMD-TYPE .
ZSWL_V_PARMD-SIGN =
ZSWL_T_PARMD-SIGN .
ZSWL_V_PARMD-OPT =
ZSWL_T_PARMD-OPT .
ZSWL_V_PARMD-LOW =
ZSWL_T_PARMD-LOW .
ZSWL_V_PARMD-HIGH =
ZSWL_T_PARMD-HIGH .
ZSWL_V_PARMD-VALIDFROM =
ZSWL_T_PARMD-VALIDFROM .
ZSWL_V_PARMD-VALIDUNTIL =
ZSWL_T_PARMD-VALIDUNTIL .
ZSWL_V_PARMD-REMARK =
ZSWL_T_PARMD-REMARK .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSWL_V_PARMD USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSWL_V_PARMD-LGNUM TO
ZSWL_T_PARMD-LGNUM .
MOVE ZSWL_V_PARMD-ID1 TO
ZSWL_T_PARMD-ID1 .
MOVE ZSWL_V_PARMD-ID2 TO
ZSWL_T_PARMD-ID2 .
MOVE ZSWL_V_PARMD-TYPE TO
ZSWL_T_PARMD-TYPE .
MOVE ZSWL_V_PARMD-SEQNO TO
ZSWL_T_PARMD-SEQNO .
MOVE ZSWL_V_PARMD-MANDT TO
ZSWL_T_PARMD-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSWL_T_PARMD'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSWL_T_PARMD TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSWL_T_PARMD'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
