*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 31.03.2020 at 09:58:05
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZSWL_V_SW_CRIT..................................*
FORM GET_DATA_ZSWL_V_SW_CRIT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSWL_T_SW_CRIT WHERE
(VIM_WHERETAB) .
    CLEAR ZSWL_V_SW_CRIT .
ZSWL_V_SW_CRIT-MANDT =
ZSWL_T_SW_CRIT-MANDT .
ZSWL_V_SW_CRIT-LGNUM =
ZSWL_T_SW_CRIT-LGNUM .
ZSWL_V_SW_CRIT-IPNUM =
ZSWL_T_SW_CRIT-IPNUM .
ZSWL_V_SW_CRIT-COMBINATION =
ZSWL_T_SW_CRIT-COMBINATION .
ZSWL_V_SW_CRIT-FIELD =
ZSWL_T_SW_CRIT-FIELD .
ZSWL_V_SW_CRIT-FIELD_VALUE =
ZSWL_T_SW_CRIT-FIELD_VALUE .
ZSWL_V_SW_CRIT-XACTIVE =
ZSWL_T_SW_CRIT-XACTIVE .
<VIM_TOTAL_STRUC> = ZSWL_V_SW_CRIT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSWL_V_SW_CRIT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSWL_V_SW_CRIT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSWL_V_SW_CRIT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSWL_T_SW_CRIT WHERE
  LGNUM = ZSWL_V_SW_CRIT-LGNUM AND
  IPNUM = ZSWL_V_SW_CRIT-IPNUM AND
  COMBINATION = ZSWL_V_SW_CRIT-COMBINATION AND
  FIELD = ZSWL_V_SW_CRIT-FIELD AND
  FIELD_VALUE = ZSWL_V_SW_CRIT-FIELD_VALUE .
    IF SY-SUBRC = 0.
    DELETE ZSWL_T_SW_CRIT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSWL_T_SW_CRIT WHERE
  LGNUM = ZSWL_V_SW_CRIT-LGNUM AND
  IPNUM = ZSWL_V_SW_CRIT-IPNUM AND
  COMBINATION = ZSWL_V_SW_CRIT-COMBINATION AND
  FIELD = ZSWL_V_SW_CRIT-FIELD AND
  FIELD_VALUE = ZSWL_V_SW_CRIT-FIELD_VALUE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSWL_T_SW_CRIT.
    ENDIF.
ZSWL_T_SW_CRIT-MANDT =
ZSWL_V_SW_CRIT-MANDT .
ZSWL_T_SW_CRIT-LGNUM =
ZSWL_V_SW_CRIT-LGNUM .
ZSWL_T_SW_CRIT-IPNUM =
ZSWL_V_SW_CRIT-IPNUM .
ZSWL_T_SW_CRIT-COMBINATION =
ZSWL_V_SW_CRIT-COMBINATION .
ZSWL_T_SW_CRIT-FIELD =
ZSWL_V_SW_CRIT-FIELD .
ZSWL_T_SW_CRIT-FIELD_VALUE =
ZSWL_V_SW_CRIT-FIELD_VALUE .
ZSWL_T_SW_CRIT-XACTIVE =
ZSWL_V_SW_CRIT-XACTIVE .
    IF SY-SUBRC = 0.
    UPDATE ZSWL_T_SW_CRIT ##WARN_OK.
    ELSE.
    INSERT ZSWL_T_SW_CRIT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSWL_V_SW_CRIT-UPD_FLAG,
STATUS_ZSWL_V_SW_CRIT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSWL_V_SW_CRIT.
  SELECT SINGLE * FROM ZSWL_T_SW_CRIT WHERE
LGNUM = ZSWL_V_SW_CRIT-LGNUM AND
IPNUM = ZSWL_V_SW_CRIT-IPNUM AND
COMBINATION = ZSWL_V_SW_CRIT-COMBINATION AND
FIELD = ZSWL_V_SW_CRIT-FIELD AND
FIELD_VALUE = ZSWL_V_SW_CRIT-FIELD_VALUE .
ZSWL_V_SW_CRIT-MANDT =
ZSWL_T_SW_CRIT-MANDT .
ZSWL_V_SW_CRIT-LGNUM =
ZSWL_T_SW_CRIT-LGNUM .
ZSWL_V_SW_CRIT-IPNUM =
ZSWL_T_SW_CRIT-IPNUM .
ZSWL_V_SW_CRIT-COMBINATION =
ZSWL_T_SW_CRIT-COMBINATION .
ZSWL_V_SW_CRIT-FIELD =
ZSWL_T_SW_CRIT-FIELD .
ZSWL_V_SW_CRIT-FIELD_VALUE =
ZSWL_T_SW_CRIT-FIELD_VALUE .
ZSWL_V_SW_CRIT-XACTIVE =
ZSWL_T_SW_CRIT-XACTIVE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSWL_V_SW_CRIT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSWL_V_SW_CRIT-LGNUM TO
ZSWL_T_SW_CRIT-LGNUM .
MOVE ZSWL_V_SW_CRIT-IPNUM TO
ZSWL_T_SW_CRIT-IPNUM .
MOVE ZSWL_V_SW_CRIT-COMBINATION TO
ZSWL_T_SW_CRIT-COMBINATION .
MOVE ZSWL_V_SW_CRIT-FIELD TO
ZSWL_T_SW_CRIT-FIELD .
MOVE ZSWL_V_SW_CRIT-FIELD_VALUE TO
ZSWL_T_SW_CRIT-FIELD_VALUE .
MOVE ZSWL_V_SW_CRIT-MANDT TO
ZSWL_T_SW_CRIT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSWL_T_SW_CRIT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSWL_T_SW_CRIT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSWL_T_SW_CRIT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
